name: CI/CD Deployment pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:  
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for vulnerabilities
        run: bin/brakeman --no-pager
  
  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run RuboCop
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env: 
          POSTGRES_DB: url_shortener_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports: 
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps: 
      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install --no-install-recommends -y \
          build-essential libpq-dev

      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run RSpec test
        env:
          RAILS_ENV: test
          DB_USER: postgres
          DB_PASSWORD: password
          DB_URL: postgres://postgres:password@localhost:5432/url_shortener_test
          SECRET_KEY_BASE: test
          SHORT_URL_HOST: ${{ vars.SHORT_URL_HOST }}

        run: |
          bin/rails db:test:prepare
          bundle exec rspec --backtrace
  deploy:
    needs: [security_scan, lint, test]
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Execute Deployment commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script_stop: true

          script: |
            echo "Successfully connected to Hetzner VPS"
            cd /var/www/url-shortener
            
            echo "Fetching latest changes"
            git fetch origin master
            git reset --hard origin/master
            
            echo "Configuring bundler"
            bundle config set --local path 'vendor/bundle'
            bundle config set --local without 'development test'

            echo "Loading production environment variables"
            set -a # automatically export all variables
            source /etc/default/url-shortener
            set +a

            echo "Installing production gems"
            RAILS_ENV=production bundle install

            echo "Running database migrations"
            RAILS_ENV=production bin/rails db:migrate

            echo "Restarting aplication service"
            sudo /usr/bin/systemctl restart url-shortener

            echo "Deployment completed"